# Generated by Django 4.2 on 2023-04-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room_state',
            fields=[
                ('room_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='room_id')),
                ('gas01', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas01')),
                ('gas02', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas02')),
                ('gas03', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas03')),
                ('gas04', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas04')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('room_no', models.IntegerField(blank=True, null=True, verbose_name='room_no')),
            ],
        ),
    ]
