# Generated by Django 4.2 on 2023-05-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas01', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas01')),
                ('gas02', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas02')),
                ('gas03', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas03')),
                ('gas04', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas04')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.room')),
            ],
        ),
    ]
