# Generated by Django 4.2 on 2024-08-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_state',
            name='time',
            field=models.TimeField(null=True, verbose_name='time'),
        ),
    ]
