# Generated by Django 4.2 on 2023-05-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('labour_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='labour_id')),
                ('labour_name', models.CharField(max_length=50, verbose_name='labour_name')),
                ('phone_no', models.PositiveIntegerField(verbose_name='labour_phone_no')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='manager_id')),
                ('manager_name', models.CharField(max_length=50, verbose_name='manager_name')),
                ('phone_no', models.PositiveIntegerField(verbose_name='manager_phone_no')),
                ('email', models.EmailField(max_length=254, verbose_name='manager_email')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='room_id')),
                ('room_no', models.PositiveIntegerField(verbose_name='room_no')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisor_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='supervisor_id')),
                ('supervisor_name', models.CharField(max_length=50, verbose_name='supervisor_name')),
                ('phone_no', models.PositiveIntegerField(verbose_name='supervisor_phone_no')),
                ('email', models.EmailField(max_length=254, verbose_name='supervisor_email')),
            ],
        ),
        migrations.CreateModel(
            name='RoomLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.labour', verbose_name='labour_id')),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.room', verbose_name='room_id')),
            ],
        ),
    ]
