# Generated by Django 4.2 on 2024-08-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='phone_no',
            field=models.BigIntegerField(verbose_name='labour_phone_no'),
        ),
    ]
