# Generated by Django 4.2 on 2024-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_labour_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='phone_no',
            field=models.PositiveBigIntegerField(verbose_name='supervisor_phone_no'),
        ),
    ]
