# Generated by Django 4.2 on 2024-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_supervisor_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_no',
            field=models.PositiveBigIntegerField(verbose_name='manager_phone_no'),
        ),
    ]
